prefixWithReleaseName:
  enabled: false
services:
- name: web-app
  image:
    repository: "shivani446/web-app"
    tag: 0.0.1
    pullPolicy: IfNotPresent
  ports:
  - name: http
    containerPort: 5000
  command: ["python", "app.py"]
  healthcheck:
    enabled: false
  service:
    enabled: true
    ports:
    - port: 5000
      targetPort: http
      name: http
    securityContext:
      readOnlyRootFilesystem: false
      runAsNonRoot: false
      runAsUser: 0
      runAsGroup: 0
  ingress:
    enabled: true
    className: nginx
    hosts:
    - host: shivani.signiance.com
      paths:
      - path: /
        pathType: Prefix
        servicePort: http
